[3주차 웹 기초 스터디] 윤지원
APPS-sookmyung/2024-1-Web-Basic-Study pull request #42
Opened 2024-04-27 06:50 UTC by rosaze

2주차 과제의 html, css파일을 3주차 폴더로 옮겨서 과제를 진행했습니다.

2024-05-01 10:24 UTC, ajung7038 requested changes
정말 너무 수고하셨습니다! 수정할 부분은 코멘트로 달아두었으니 수정해주시면 될 것 같습니다~

2024-05-01 10:24 UTC, ajung7038 commented on 윤지원/3주차 과제/thirdweek.js
> +  const pokemons = document.querySelectorAll(".container .pokemons .pokemon");
querySelectorAll을 활용해 문제를 해결하신 점 너무 좋습니다~

2024-05-01 10:24 UTC, ajung7038 commented on 윤지원/3주차 과제/thirdweek.js
> +    return Math.floor(Math.random() * 1000) + 1;
요구사항대로 Math.floor, Math,random 함수를 활용해 무작위로 능력치를 생성해주신 점 좋습니다!

2024-05-01 10:24 UTC, ajung7038 commented on 윤지원/3주차 과제/thirdweek.js
> +    }
하나씩 비교해주신 점 좋아요! 그러나 JS의 어떤 특징을 이용하면 조금 더 간단하게 만들 수 있어요! 29-34번째 줄을 단 한 줄로 고쳐주세요.

2024-05-06 06:35 UTC, ajung7038 approved these changes
너무 수고하셨습니다! 중간에 깃허브 때문에 고생하셨을 텐데 정말 잘 해결해 주셨네요! 머지하겠습니다~

2024-05-06 06:35 UTC, ajung7038 commented on 윤지원/3주차 과제/thirdweek.js
> +    if (isNaN(monster1) || isNaN(monster2)) {
isNaN 함수를 사용하여 한 줄로 잘 줄여주셨어요! 참고로, JS 문법인 truthy, falsy 문법을 활용하여 간결하게 나타낼 수도 있답니다!

2024-05-06 06:35 UTC, merged

2024-05-06 06:36 UTC, rosaze commented
도와주셔서 감사합니다!!😍

2024년 5월 6일 (월) 오후 3:35, 아정 ***@***.***>님이 작성:

> Merged #42
> <https://github.com/APPS-sookmyung/2024-1-Web-Basic-Study/pull/42> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/APPS-sookmyung/2024-1-Web-Basic-Study/pull/42#event-12710573682>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A75CBGOUXA67GCUE3M7F55DZA4QEZAVCNFSM6AAAAABG33I2AOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSG4YTANJXGM3DQMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <APPS-sookmyung/2024-1-Web-Basic-Study/pull/42/issue_event/12710573682@
> github.com>
>