[3주차 웹 기초 스터디] 윤정란
APPS-sookmyung/2024-1-Web-Basic-Study pull request #43
Opened 2024-04-28 05:24 UTC by yoon-jr

2024-05-01 10:31 UTC, ajung7038 requested changes
정말 너무 수고하셨습니다! 너무 잘 구현하셨어요!! 수정 해야 할 부분을 코멘트로 적어두었으니, 확인 부탁드립니다~

2024-05-01 10:31 UTC, ajung7038 commented on 윤정란/3주차 과제/page.js
> +});
forEach 문을 사용하여 잘 작성해주셨어요! addEventListener과 querySelectorAll을 사용해 클릭 이벤트를 잘 구현해주셨네요 ☺️☺️

2024-05-01 10:31 UTC, ajung7038 commented on 윤정란/3주차 과제/page.js
> +  }
잘못된 숫자 입력 시 오류 문구를 띄우는 것도 잘 처리해주셨는데, 20~23번째 줄을 더 간결하게 입력할 수 있답니다! 단 한 줄로 수정할 수 있으니, JS의 특징을 활용해 한 줄로 다시 표현해주세요!

2024-05-01 10:31 UTC, ajung7038 commented on 윤정란/3주차 과제/page.js
> +}
요구사항에 따라 각 포켓몬의 능력치를 잘 비교해주셨어요! prompt와 alert를 활용하신 점 좋습니다!

2024-05-06 01:05 UTC, yoon-jr commented
범위 확인 코드 수정했습니다

2024-05-06 06:38 UTC, ajung7038 approved these changes
너무 고생하셨습니다~ 머지할게요!

2024-05-06 06:38 UTC, ajung7038 commented on 윤정란/3주차 과제/page.js
> +  if ((monster1 && monster2) < 0 || (monster1 && monster2) > 31) {
한 줄로 잘 수정하셨네요! 참고로 JS 문법 truthy, falsy 문법을 활용해도 한 줄로 줄일 수 있답니다~

2024-05-06 06:40 UTC, merged