[3주차 웹 기초 스터디] 윤서빈
APPS-sookmyung/2024-1-Web-Basic-Study pull request #44
Opened 2024-04-28 11:40 UTC by seobin0224

처음에 버튼 크기가 너무 크게 나와서 css나 js로 고쳐야하나 고민하다 html에서 <button></button> 의 위치를 container 아래에 넣었더니 해결이되었다.

2024-05-01 10:37 UTC, ajung7038 requested changes
너무 수고하셨습니다~ 수정할 부분은 코멘트로 달아두었으니 확인 부탁드려요!

2024-05-01 10:37 UTC, ajung7038 commented on 윤서빈/3주차_실습/power.js
> +  }
함수와 Math.floor, Math.random 함수를 활용해 랜덤 값을 잘 부여해주셨네요!

2024-05-01 10:37 UTC, ajung7038 commented on 윤서빈/3주차_실습/power.js
> +  });
for문을 넘어서 forEach문을 활용하신 점 정말 인상 깊습니다! PPT에 짧게 설명했던 템플릿 리터럴 문법을 사용하신 점도 좋아요!

2024-05-01 10:37 UTC, ajung7038 commented on 윤서빈/3주차_실습/power.js
> +    }
값이 올바르지 않을 때에 대한 if문도 잘 처리해주셨네요! 그러나 JS의 어떤 문법을 이용하면 24-29번째 줄을 한 번에 처리 가능하답니다~ 한 줄로 수정해주세요!

2024-05-01 10:37 UTC, ajung7038 commented on 윤서빈/3주차_실습/power.js
> +      alert("능력치가 동일합니다");
포켓몬 능력치 비교 코드를 alert와 prompt로 잘 처리해주셨어요!

2024-05-02 04:57 UTC, seobin0224 commented on 윤서빈/3주차_실습/power.js
> +    }
수정했습니다~

2024-05-03 10:17 UTC, ajung7038 approved these changes
수정 확인했습니다. 머지할게요!

2024-05-03 10:17 UTC, ajung7038 commented on 윤서빈/3주차_실습/power.js
> +      )
.some() 함수를 활용해 코드를 한 줄로 잘 수정해 주셨네요! 참고로, 자바의 truthy, falsy 특징을 활용해 이러한 문제를 해결 할 수도 있답니다!

2024-05-03 10:17 UTC, merged