[3주차 웹 기초 스터디]
APPS-sookmyung/2024-1-Web-Basic-Study pull request #55
Opened 2024-04-30 14:37 UTC by janguzin

능력치 비교 버튼을 누르고 포켓몬들의 번호를 각각 입력 후 비교 창이 뜰 때 매번 "능력치가 동일합니다." 이 멘트만 출력이 됩니다.
이 부분이 해결이 안되어 일단 능력치 비교 부분만 미완 상태로 제출합니다!

2024-05-01 12:14 UTC, ajung7038 requested changes
능력치가 동일하다는 문구는 아마 poketmonStmts 배열에 포켓몬의 랜덤한 값을 부여하지 않았기 때문인 것 같아요. 배열이 빈 배열이어서 아무 값도 없으므로 당연히 능력치가 동일하다고 나오겠죠? 수정 사항을 적어두었으니 보시고 수정해 주세요~!! 너무 수고하셨습니다!

2024-05-01 12:14 UTC, ajung7038 commented on 장유진/3주차 과제/index.html
> +    <script src="index.js"></script>
외부 JS 파일과 연결 잘 하셨어요! 틀린 건 아니지만, JS 파일명은 구현 기능에 따라가는 것이 나중에 파악하기도, 이해하기도 쉬워요. 예를 들면 덧셈과 관련된 js 파일명을 add.js로 하는 것처럼요! 이러한 예에 맞춰 js 파일명을 변환해 주세요!

2024-05-01 12:14 UTC, ajung7038 commented on 장유진/3주차 과제/index.js
> +});
addEventListener을 활용해 포켓몬의 능력치가 나오는 부분을 잘 구현해 주셨네요!

2024-05-01 12:14 UTC, ajung7038 commented on 장유진/3주차 과제/index.js
> +document.querySelector('.container').appendChild(compareButton);
능력치 비교 관련 button을 아주 잘 만들어 주셨어요! 그러나 관습 상 버튼은 html에 구현하는 것이 더 좋답니다. 물론 틀린 건 아니에요! 그렇지만 기능과 역할이 분리되어 있다면 나중에 더 찾기 쉽겠죠? button을 index.js 파일이 아닌 index.html 파일에 구현해 보세요! (수정 필요)

2024-05-01 12:14 UTC, ajung7038 commented on 장유진/3주차 과제/index.js
> +  }
값이 올바른지 아닌지 판별하는 로직을 잘 작성하셨어요! 그런데 JS 문법을 활용하면 이러한 코드를 더 간결하게 작성할 수 있답니다! JS 문법을 활용해 한 줄로 코드를 작성해 주세요!

2024-05-02 04:46 UTC, janguzin reviewed
말씀해주신 부분 수정했습니다! 감사합니다!

2024-05-03 10:33 UTC, ajung7038 approved these changes
너무 수고하셨어요~! 수정 사항 확인 완료했으니 머지하겠습니다!

2024-05-03 10:33 UTC, ajung7038 commented on 장유진/3주차 과제/pokemon.js
> +      const pokemonName = pokemons[index].getAttribute('class');
능력치를 배열에 담는 부분을 구현해 내셨네요~! 요구사항에 맞춰 배열과 함수를 쓰신 점 좋습니다~!

2024-05-03 10:33 UTC, ajung7038 commented on 장유진/3주차 과제/pokemon.js
> +    if (![pokemon1, pokemon2].every(pokemon => !isNaN(pokemon) && pokemon >= 0 && pokemon < pokemons.length)) {
.every() 함수를 사용해 참값인지 확인한 점 좋아요~ 참고로, 원래의 의도는 JS truthy, falsy 문법을 활용해 문제를 해결하는 것이었답니다!

2024-05-03 10:34 UTC, merged